# Example configuration for Black.

# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.
[tool.pytest.ini_options]
minversion = "6.1"
addopts = "-ra -q"
testpaths = "tests"

[tool.flake8]
ignore = ['E203', 'E266', 'E501', 'W503', 'F403', 'F401', 'E231']
max-line-length = 120
max-complexity = 18
select = ['B','C','E','F','W','T4','B9']

[tool.isort]
known_third_party = ["matplotlib", "nltk", "numpy", "pandas", "requests", "scipy", "seaborn", "sklearn", "src", "tqdm"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120

[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
)/
'''
